---
title: " "
---

<br>
<br>
<br>
<br>
<br>

# Course content and reading lists
*Note*: .html i .Rmd formats can be accessed from the  [repository](https://github.com/lusiki/Learning-Social-Media-Analytics).
<br>
<br>
<br>
<br>



### Lecture 01: Course introduction


- General course information
- Objectives of the course
- Course Literature
- Data and resources

<br>
**Format:** [.html](https://raw.githack.com/lusiki/Learning-Social-Media-Analytics/main/lectures/Regular%20Classes/Lecture-1-Course-introduction.html) | [.rmd](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/lectures/Regular%20Classes/Lecture%201%20Course%20introduction.Rmd)
<br>
**Readings:**  [thoroughly check the course website/resources](https://lusiki.github.io/Learning-Social-Media-Analytics/index.html)
<br>
<br>

### Lecture 02: Current state and latest trends in the social media space

- Data overview
- Facebook
- Web
- Twitter
- Youtube
- Forum
- Instagram

<br>
**Format:** [.html](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/lectures/Regular%20Classes/Lecture-2-State-and-trends.html) | [.Rmd](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/lectures/Regular%20Classes/Lecture%202%20State%20and%20trends.Rmd) 
<br>
**Readings:** [try out mediatoolkit data sample](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/data/Mediatoolkit/sample.xlsx)
<br>
<br>

### Lecture 03: Data Science Prerequisites

- Fetching data
- Storing data
- Manipulating
- Analytics
- Reporting

**Format:** [.html](https://raw.githack.com/lusiki/Learning-Social-Media-Analytics/main/lectures/Regular%20Classes/Lecture-3-Data-Science-Prerequisites.html) | [.md](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/lectures/Regular%20Classes/Lecture-3-Data-Science-Prerequisites.md) 
<br>
**Readings:** []() + []()
<br>
<br>



### Lecture 04: R syntax refresher 

-
-  
- 


**Format predavanja:** [.html]()) | [.Rmd]() 
<br>
**Čitanje:** []() + []()
<br>
<br>

### Lecture 05: Methods for social media analysis I (descriptive statistics, visualization)

- 
- 
- 


**Format predavanja:** [.html]() | [.Rmd]() 
<br>
**Čitanje:** []()
<br>
<br>

### Lecture 06: Methods for social media analysis II (network analysis, Natural Language Processing)

- 
- 
- 



**Format predavanja:** [.html]() | [.Rmd]() 
<br>
**Čitanje:** []]() + []() + []()
<br>
<br>


### Lecture 07: Methods for social media analysis III (time series, machine learning, deep learning, neural networks)

- 
- 
- 

**Format predavanja:** [.html]()) | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>

### Lecture 08: General principles of digital marketing (key performance indicators, search engine optimization, social media listening)

- 
- 
-



**Format predavanja:** [.html]() | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>

### Lecture 09: Twitter - trend formation and event detection

- 
- 
- 


**Format predavanja:** [.html]() | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>

### Lecture 10: Facebook - analysis of the institutional, political and brand reach

- 
- 
- 


**Format predavanja:** [.html]() | [.Rmd]) 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>


### Lecture 11: Instagram - influencer market space and image recognition

- 
- 
- 


**Format predavanja:** [.html] | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>


### Lecture 12: LinkedIn - business network and geolocation analysis

- 
- 
- 


**Format predavanja:** [.html] | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>



### Lecture 13: Online portals and forums - text analysis and application od NLP methods

- 
- 
- 


**Format predavanja:** [.html] | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>

### Lecture 14: Traditional media (newspaper, TV, radio) - public sentiment analysis and opinion polarity

- 
- 
- 


**Format predavanja:** [.html] | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>


### Lecture 15: Future trends in social media

- 
- 
- 


**Format predavanja:** [.html] | [.Rmd]() 
<br>
**Čitanje:** []() + []() + []()
<br>
<br>
