---
title: "Katoličke dezinformacije"
author: "Lux"
date: "2023-03-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r echo=F, eval=T, message=F , warning= FALSE, message=F}
library(tidyverse)
library(readxl)
library(xlsx)
library(here)
library(kableExtra)
library(DT)
library(purrr)
library(data.table)
library(tidytext)
library(dplyr)
library(lubridate)
library(anytime)
library(grid)
library(wordcloud)
library(reshape2)
library(ggraph)
library(widyr)
library(topicmodels)
library(ggthemes)
library(xlsx)
library(writexl)

```

```{r echo=F, eval=F, message=F , warning= FALSE}
# fullDta <- fread("D:/LUKA/Freelance/Mediatoolkit/FULLDATA_NOTXT.csv")
# fullDtaTxt <- fread("D:/LUKA/Freelance/Mediatoolkit/FULLDATA_TXT.csv")
all <- fread("D:/LUKA/Freelance/Mediatoolkit/MktFULLtxt.csv")
# 
#all <- all %>% mutate(V1 = as.numeric(V1))
# dt <- dt %>% filter(SOURCE_TYPE == "web") %>%
#   distinct(URL,.keep_all = TRUE)
# 
# dt <- dt %>%
#   mutate(V1 = as.numeric(V1)) %>%
#   distinct(V1, .keep_all = T)# %>%
#  # slice(1:300000) 

dt <- read_excel("D:/LUKA/Freelance/Mediatoolkit/catholiq.xlsx") %>% select(-match)

#write_xlsx(dt, "D:/LUKA/Freelance/Mediatoolkit/catholiq.xlsx")
```


```{r echo=F, eval=F, message=F , warning= FALSE}
catoliq <- dt %>% select(V1,key_word)
dt <- left_join(catoliq, all, by = "V1")
dt$DATE <- as.Date(dt$DATE.x)
rm(all)
```

```{r echo=F, eval=F, message=F , warning= FALSE}
dt <- read_excel("D:/LUKA/Freelance/Mediatoolkit/catholiq.xlsx") 

```





```{r}

dt <- fread("D:/LUKA/Freelance/Mediatoolkit/MktFULLtxt.csv")


setDT(df)
"D:/LUKA/Academic/HKS/Projekti/Dezinformacije/Data/katolički_izrazi.xlsx"
# Words vector (for simplicity, using a shortened version)
words_vector <- c("anglican", "atheist", "baptist", "catholic", "biskup rima" )


df[, `:=` (has_match = sapply(text, function(x) any(sapply(words_vector, grepl, x))),
           matched_words = sapply(text, function(x) paste(words_vector[sapply(words_vector, grepl, x)], collapse=", ")))]

```




#### Deskriptiva na dnevnoj razini
```{r echo=F, eval=T, message=F , warning= FALSE}
# articles over time
daily_counts <- dt %>%
  group_by(DATE) %>%
  summarise(count = n())

# descriptives 
summ <- daily_counts %>% 
  summarize(min = min(count), max = max(count), 
            mean = mean(count), q1= quantile(count, probs = 0.25), 
            median = median(count), q3= quantile(count, probs = 0.75),
            sd = sd(count)) %>%
  mutate_if(is.numeric, round, digits=2) 

summ
```



#### Broj objava po danima  
```{r echo=F, eval=T, message=F , warning= FALSE}
# create plot of articles over time
ggplot(data = daily_counts, aes(x = DATE, y = count)) +
  geom_line() +
  labs(x = "Date", y = "Number of Articles")
 

```


#### Broj objava po izvoru 
```{r echo=F, eval=T, message=F , warning= FALSE}
# Portals by activity
activity <- dt %>%
  group_by(FROM) %>%
  summarise(count = n()) %>%
  mutate(percent = round(count / sum(count) * 100,2)) %>% 
  arrange(desc(count))

datatable(activity, options = list(scrollX = TRUE, scrollY = "500px"))
```

# Text analysis 

```{r echo=F, eval=T, message=F , warning= FALSE}
# read in lexicons
CroSentilex_n <- read.delim("C:/Users/Lukas/Dropbox/Mislav@Luka/crosentilex-negatives.txt",
                                   header = FALSE,
                                   sep = " ",
                                   stringsAsFactors = FALSE,
                                   fileEncoding = "UTF-8")  %>%
                   rename(word = "V1", sentiment = "V2" ) %>%
                   mutate(brija = "NEG")
 
CroSentilex_p  <- read.delim("C:/Users/Lukas/Dropbox/Mislav@Luka/crosentilex-positives.txt",
                                   header = FALSE,
                                   sep = " ",
                                   stringsAsFactors = FALSE,
                                   fileEncoding = "UTF-8") %>%
                    rename(word = "V1", sentiment = "V2" ) %>%
                    mutate(brija = "POZ")
 
Crosentilex_sve <- rbind(setDT(CroSentilex_n), setDT(CroSentilex_p))
# check lexicon data 
#head(sample_n(Crosentilex_sve,1000),15)

 
CroSentilex_Gold  <- read.delim2("C:/Users/Lukas/Dropbox/Mislav@Luka/gs-sentiment-annotations.txt",
                                 header = FALSE,
                                 sep = " ",
                                 stringsAsFactors = FALSE) %>%
                    rename(word = "V1", sentiment = "V2" ) 
 Encoding(CroSentilex_Gold$word) <- "UTF-8"
 CroSentilex_Gold[1,1] <- "dati"
 CroSentilex_Gold$sentiment <- str_replace(CroSentilex_Gold$sentiment , "-", "1")
 CroSentilex_Gold$sentiment <- str_replace(CroSentilex_Gold$sentiment , "\\+", "2")
 CroSentilex_Gold$sentiment <- as.numeric(unlist(CroSentilex_Gold$sentiment))
# check lexicon data 
#head(sample_n(CroSentilex_Gold,100),15)

 
 
LilaHR  <- read.xlsx2("C:/Users/Lukas/Dropbox/Mislav@Luka/lilaHR_clean.xlsx", sheetIndex = 1)
  
# create stop words
stopwords_cro <- get_stopwords(language = "hr", source = "stopwords-iso")
# check stopwords data
#head(sample_n(stopwords_cro,100),15)
# extend stop words
my_stop_words <- tibble(
  word = c(
    "jedan","mjera", "može", "možete", "mogu", "kad", "sada", "treba", "ima", "osoba",
    "e","prvi", "dva","dvije","drugi",
    "tri","treći","pet","kod",
    "ove","ova",  "ovo","bez", "kod",
    "evo","oko",  "om", "ek",
    "mil","tko","šest", "sedam",
    "osam",   "čim", "zbog",
    "prema", "dok","zato", "koji", 
    "im", "čak","među", "tek",
    "koliko", "tko","kod","poput", 
    "baš", "dakle", "osim", "svih", 
    "svoju", "odnosno", "gdje",
    "kojoj", "ovi", "toga","u", "ne", "su",
     "ubera", "vozača", "hrvatskoj", "usluge", "godine", "više", "taksi", "taxi", "taksija", "taksija", "kaže", "rekao", "19"," aee", "ae","bit.ly", "https", "one", "the"
  ),
  lexicon = "lux"
)

words_vector <- c(
"a",
"ako",
"ali",
"bi",
"bih",
"bila",
"bili",
"bilo",
"bio",
"bismo",
"biste",
"biti",
"bumo",
"da",
"do",
"duž",
"ga",
"hoće",
"hoćemo",
"hoćete",
"hoćeš",
"hoću",
"i",
"iako",
"ih",
"ili",
"iz",
"ja",
"je",
"jedna",
"jedne",
"jedno",
"jer",
"jesam",
"jesi",
"jesmo",
"jest",
"jeste",
"jesu",
"jim",
"joj",
"još",
"ju",
"kada",
"kako",
"kao",
"koja",
"koje",
"koji",
"kojima",
"koju",
"kroz",
"li",
"me",
"mene",
"meni",
"mi",
"mimo",
"moj",
"moja",
"moje",
"mu",
"na",
"nad",
"nakon",
"nam",
"nama",
"nas",
"naš",
"naša",
"naše",
"našeg",
"ne",
"nego",
"neka",
"neki",
"nekog",
"neku",
"nema",
"netko",
"neće",
"nećemo",
"nećete",
"nećeš",
"neću",
"nešto",
"ni",
"nije",
"nikoga",
"nikoje",
"nikoju",
"nisam",
"nisi",
"nismo",
"niste",
"nisu",
"njega",
"njegov",
"njegova",
"njegovo",
"njemu",
"njezin",
"njezina",
"njezino",
"njih",
"njihov",
"njihova",
"njihovo",
"njim",
"njima",
"njoj",
"nju",
"no",
"o",
"od",
"odmah",
"on",
"ona",
"oni",
"ono",
"ova",
"pa",
"pak",
"po",
"pod",
"pored",
"prije",
"s",
"sa",
"sam",
"samo",
"se",
"sebe",
"sebi",
"si",
"smo",
"ste",
"su",
"sve",
"svi",
"svog",
"svoj",
"svoja",
"svoje",
"svom",
"ta",
"tada",
"taj",
"tako",
"te",
"tebe",
"tebi",
"ti",
"to",
"toj",
"tome",
"tu",
"tvoj",
"tvoja",
"tvoje",
"u",
"uz",
"vam",
"vama",
"vas",
"vaš",
"vaša",
"vaše",
"već",
"vi",
"vrlo",
"za",
"zar",
"će",
"ćemo",
"ćete",
"ćeš",
"ću",
"što"
)

# full set with diacritics
cro_sw_full_d <- c("a","ako","ali","baš","bez","bi","bih","bila","bili","bilo","bio","bismo","bit","biti","bolje","bude","čak","čega","čemu","često","četiri","čime","čini","će","ćemo","ćete","ću","da","dakle","dalje","dan","dana","dana","danas","dio","do","dobro","dok","dosta","dva","dvije","eto","evo","ga","gdje","god","godina","godine","gotovo","grada","i","iako","ići","ih","ili","im","ima","imaju","imali","imam","imao","imati","inače","ipak","isto","iz","iza","između","ja","jako","je","jedan","jedna","jednog","jednom","jednostavno","jednu","jer","joj","još","ju","ka","kad","kada","kaj","kako","kao","kaže","kod","koja","koje","kojeg","kojeg","kojem","koji","kojih","kojim","kojima","kojoj","kojom","koju","koliko","kraju","kroz","li","malo","manje","me","među","međutim","mene","meni","mi","milijuna","mislim","mjesto","mnogo","mogao","mogli","mogu","moj","mora","možda","može","možemo","možete","mu","na","način","nad","naime","nakon","nam","naravno","nas","ne","neće","nego","neka","neke","neki","nekog","nekoliko","neku","nema","nešto","netko","ni","nije","nikad","nisam","nisu","ništa","niti","no","njih","o","od","odmah","odnosno","oko","on","ona","onda","oni","onih","ono","opet","osim","ova","ovaj","ovdje","ove","ovim","ovo","ovog","ovom","ovu","pa","pak","par","po","pod","poput","posto","postoji","pred","preko","prema","pri","prije","protiv","prvi","puno","put","radi","reći","s","sa","sad","sada","sam","samo","sati","se","sebe","si","smo","ste","stoga","strane","su","svaki","sve","svi","svih","svoj","svoje","svoju","što","ta","tada","taj","tako","također","tamo","te","tek","teško","ti","tih","tijekom","time","tko","to","tog","toga","toj","toliko","tom","tome","treba","tu","u","uopće","upravo","uvijek","uz","vam","vas","već","vi","više","vrijeme","vrlo","za","zapravo","zar","zato","zbog","zna","znači")

stop_corpus <- my_stop_words %>%
  bind_rows(stopwords_cro)
# check stopwords data
#head(sample_n(stop_corpus,100),15)





```





```{r echo=F, eval=F, message=F , warning= FALSE}

stop=c('biti','jesam','budem','sam','jesi','budeš','si','jesmo','budemo','smo','jeste','budete','ste','jesu','budu','su','bih','bijah','bjeh','bijaše','bi','bje','bješe','bijasmo','bismo','bjesmo','bijaste','biste','bjeste','bijahu','biste','bjeste','bijahu','bi','biše','bjehu','bješe','bio','bili','budimo','budite','bila','bilo','bile','ću','ćeš','će','ćemo','ćete','želim','želiš','želi','želimo','želite','žele','moram','moraš','mora','moramo','morate','moraju','trebam','trebaš','treba','trebamo','trebate','trebaju','mogu','možeš','može','možemo','možete')



istakniSlogotvornoR <- function(niz) {
  stringr::str_replace_all(niz, "(^|[^aeiou])r($|[^aeiou])", "\\1R\\2")
}

imaSamoglasnik <- function(niz) {
  !is.na(stringr::str_detect(istakniSlogotvornoR(niz), "[aeiouR]"))
}

transformiraj <- function(pojavnica) {
  for(i in 1:nrow(transformacije)) {
    trazi <- transformacije[i, 1]
    zamijeni <- transformacije[i, 2]
    if (endsWith(pojavnica, trazi)) {
      return(sub(paste0(trazi, "$"), zamijeni, pojavnica))
    }
  }
  return(pojavnica)
}

korjenuj <- function(pojavnica) {
  for(pravilo in pravila) {
    dioba <- stringr::str_match(pojavnica, pravilo)
    if (!is.na(dioba[2])) {
      if (imaSamoglasnik(dioba[2]) && nchar(dioba[2]) > 1) {
        return(dioba[2])
      }
    }
  }
  return(pojavnica)
}

# Assuming you have 'input_file.txt' and 'output_file.txt' as your input and output
input_file <- 'input_file.txt'
output_file <- 'output_file.txt'

pravila <- lapply(strsplit(trimws(readLines('C:/Users/Lukas/Dropbox/Mislav@Luka/rules.txt')), ' '), function(x) paste0('^(', x[1], ')(', x[2], ')$'))
transformacije <- as.data.frame(do.call(rbind, strsplit(trimws(readLines('C:/Users/Lukas/Dropbox/Mislav@Luka/transformations.txt')), '\t')))


#text <- n_tokenTidy$word %>% head(1000)
#text <- tolower(readLines(input_file))


#tokens <- unlist(stringi::stri_extract_all_words(text))

write_tokens <- function(token) {
  if (token %in% stop) {
    return(paste0(token, '\t', token))
  } else {
    return(paste0(token, '\t', korjenuj(transformiraj(token))))
  }
}

#results <- sapply(tokens, write_tokens)
#extracted <- sapply(strsplit(results, "\t"), `[`, 2)
#names(extracted) <- NULL
```




```{r}
genralno_root <- sapply(generalno, write_tokens)
genralno_root <- sapply(strsplit(genralno_root, "\t"), `[`, 2)


generalno <- enframe(genralno_root, name = "name", value = "root")
```











```{r echo=F, eval=T, message=F , warning= FALSE}
# dim before tokenize
#dim(dta)

# tokenize
dt %>% 
  unnest_tokens(word, FULL_TEXT) -> n_token

# dim after tokenize
#dim(n_token)

# check
# fb_token %>% 
#   select(FROM, word, MENTION_SNIPPET ) %>%
#     sample_n(.,100)

# remove stop words, numbers, single letters
n_token %>% 
  anti_join(stop_corpus, by = "word") %>%
  mutate(word = gsub("\\d+", NA, word)) %>%
  mutate(word = gsub("^[a-zA-Z]$", NA, word)) -> n_tokenTidy
# remove NA
n_tokenTidy %>%
  filter(!is.na(word)) -> n_tokenTidy

# check
# fb_tokenTidy  %>% 
#   select(FROM, word, MENTION_SNIPPET ) %>%
#   sample_n(.,100)

# dim after clean
#dim(n_tokenTidy)

```


```{r}
proba <- n_tokenTidy %>% slice(1:10000) %>%
  mutate(
    word_korijen = sapply(word, function(x) {
      result <- sapply(x, write_tokens)
      extracted <- sapply(strsplit(result, "\t"), `[`, 2)
      names(extracted) <- NULL
      return(extracted)
    })
  )



proba <- n_tokenTidy %>% slice(1:10000) %>%
  mutate(
    results = map(word, write_tokens),
    transformed_column = map_chr(results, ~ str_extract(.x, "(?<=\t)[^\t]+$"))
  ) %>%
  select(-results) 


setDT(n_tokenTidy)

n_tokenTidy[, transformed_column := sapply(strsplit(sapply(word, write_tokens), "\t"), `[`, 2)]

```





#### Najčešće riječi (>50)

```{r echo=F, eval=T, message=F , warning= FALSE, fig.height=25}
# ## Most common words
# n_tokenTidy[,.N,by = word][order(-N),] %>%
#   datatable(., options = list(scrollX = TRUE, scrollY = "500px"))

proba %>%
  group_by(word) %>%
  summarise(N = n()) %>%
  arrange(desc(N)) %>%
  filter(N > 10) %>%
  datatable(., options = list(scrollX = TRUE, scrollY = "500px"))


proba %>%
  group_by(transformed_column) %>%
  summarise(N = n()) %>%
  arrange(desc(N)) %>%
  filter(N > 10) %>%
  datatable(., options = list(scrollX = TRUE, scrollY = "500px"))


```

```{r echo=F, eval=F, message=F , warning= FALSE}

words_vector <- c(
  "anglican",
  "anglican communion",
  "apostolic",
  "apostolic succession",
  "archbishop",
  "atheist",
  "baptist",
  "benedictine",
  "bishop",
  "bishop of rome",
  "blessed sacrament",
  "broad-minded",
  "calvinist",
  "cardinal newman",
  "cathedral",
  "catholic",
  "catholic bishops",
  "catholic church",
  "catholicism",
  "christian",
  "christian denomination",
  "christianity",
  "christians",
  "church",
  "confessional",
  "congregational",
  "conservative",
  "devout",
  "diocese",
  "doctrine",
  "eastern",
  "eastern catholic churches",
  "eastern orthodox church",
  "ecclesiastical",
  "episcopal",
  "episcopalian",
  "ethics",
  "eucharist",
  "evangelical",
  "full communion",
  "fundamentalist",
  "greek language",
  "holy cross",
  "holy family",
  "holy rosary",
  "holy see",
  "holy trinity",
  "ignatius of antioch",
  "immaculate conception",
  "immaculate heart",
  "irish",
  "italian",
  "jerusalem",
  "jesuit",
  "jesuits",
  "jesus christ",
  "jewish",
  "latin liturgical rites",
  "latin rite",
  "latitudinarian",
  "liturgy",
  "lutheran",
  "melkite",
  "methodist",
  "mormon",
  "msgr",
  "muslim",
  "nationalist",
  "nicene creed",
  "nuns",
  "orthodox",
  "orthodoxy",
  "parish",
  "parishes",
  "particular church",
  "pentecost",
  "pentecostal",
  "pontiff",
  "pope",
  "presbyterian",
  "priest",
  "private",
  "protestant",
  "protestant reformation",
  "public",
  "religion",
  "religious",
  "republican",
  "roman",
  "roman catholic",
  "roman catholic church",
  "rome",
  "sacred heart",
  "salesian",
  "smyrna",
  "st. thomas aquinas",
  "theological",
  "theology",
  "tradition"
)
```


```{r echo=F, eval=F, message=F , warning= FALSE}

cro_catoliq <- c(
  "anglikanac",          # anglican
  "anglikanska zajednica", # anglican communion
  "apostolski",          # apostolic
  "apostolsko nasljeđe",  # apostolic succession
  "nadbiskup",           # archbishop
  "ateist",              # atheist
  "baptist",             # baptist
  "benediktinac",        # benedictine
  "biskup",              # bishop
  "biskup Rima",         # bishop of rome
  "blagoslovljeni sakrament", # blessed sacrament
  "blagoslovljeni",
  "sakrament",
  "širokogrudan",        # broad-minded
  "kalvinist",           # calvinist
  "kardinal Newman",     # cardinal newman
  "katedrala",           # cathedral
  "katolički",           # catholic
  "katolički biskupi",   # catholic bishops
  "katolička crkva",     # catholic church
  "katolicizam",         # catholicism
  "kršćanin",           # christian
  "kršćanska denominacija", # christian denomination
  "kršćanstvo",       # christianity
  "crkva",               # church
  "ispovjedaonica",      # confessional
  "kongregacija",    # congregational
  "konzervativac",       # conservative
  "pobožan",             # devout
  "biskupija",           # diocese
  "doktrina",            # doctrine
  "istočne katoličke crkve", # eastern catholic churches
  "istočno pravoslavna crkva", # eastern orthodox church
  "crkveni",             # ecclesiastical
  "episkopalni",         # episcopal
  "episkopalianac",      # episcopalian
  "etika",               # ethics
  "euharistija",         # eucharist
  "evanđeoski",          # evangelical
  "puna zajednica",      # full communion
  "fundamentalist",      # fundamentalist
  "grčki jezik",         # greek language
  "sveti križ",          # holy cross
  "sveta obitelj",       # holy family
  "sveta krunica",       # holy rosary
  "sveta stolica",       # holy see
  "sveto trojstvo",      # holy trinity
  "Ignacije Antiohijski", # ignatius of antioch
  "neokaljano začeće",  # immaculate conception
  "neokaljano srce",     # immaculate heart
  "Irski",               # irish
  "Talijanski",          # italian
  "Jeruzalem",           # jerusalem
  "isusovac",            # jesuit
  "isusovci",            # jesuits
  "Isus Krist",          # jesus christ
  "židov",               # jewish
  "latinske liturgijske obrede", # latin liturgical rites
  "latinski obred",      # latin rite
  "latitudinarijanac",   # latitudinarian
  "liturgija",           # liturgy
  "luteran",             # lutheran
  "melkit",              # melkite
  "metodist",            # methodist
  "mormon",              # mormon
  "msgr",                # msgr (this might remain the same as it's an abbreviation)
  "musliman",            # muslim
  "nacionalist",         # nationalist
  "nicejsko vjerovanje", # nicene creed
  "časne sestre",        # nuns
  "pravoslavac",         # orthodox
  "pravoslavlje",        # orthodoxy
  "župa",                # parish
  "župe",                # parishes
  "posebna crkva",       # particular church
  "Duhovi",              # pentecost
  "pentekostalac",       # pentecostal
  "pontif",              # pontiff
  "papa",                # pope
  "presbiterijanac",     # presbyterian
  "svećenik",            # priest
  "privatni",            # private
  "protestant",          # protestant
  "protestantska reformacija", # protestant reformation
  "javni",               # public
  "vjera",               # religion
  "vjerski",             # religious
  "republikanac",        # republican
  "rimski",              # roman
# "rim",
  "rimokatolički",       # roman catholic
  "rimokatolička crkva", # roman catholic church
  "sveto srce",          # sacred heart
  "salezijanac",         # salesian
  "Smirna",              # smyrna
  "sv. Toma Akvinski",   # st. thomas aquinas
  "teološki",            # theological
  "teologija",           # theology
  "tradicija",           # tradition
  "crkva",
  "biskup",
  "Kaptol",
  "časna sestra",
  "svećenik",
  "župnik",
  "vjernik",
  "kardinal",
  "papa",
  "sveti otac",
  "redovnik",
  "redovnica",
  "kršćanstvo",
  "vjera",
  "Gospa",
# "Bog",
  "Isus",
  "katolički",
  "misa",
  "pričest",
  "krizma",
  "grijeh",
  "vjeroučitelj",
  "vjeronauk",
  "blagoslov",
  "svjedočanstvo",
  "relikvija",
  "stigma",
  "duhovnost",
#  "don",
  "fra",
  "velečasni",
  "zaređenje",
  "krunica",
  "vjeronauk",
  "ukazanje"            # tradition
) %>% tolower()


cro_catoliq <- sapply(cro_catoliq, write_tokens)
cro_catoliq <- sapply(strsplit(cro_catoliq, "\t"), `[`, 2)

cro_catoliq <- enframe(cro_catoliq, name = "name", value = "root")


#write_xlsx(cro_catoliq,"D:/LUKA/Academic/HKS/Projekti/Dezinformacije/Data/katolički_izrazi.xlsx")



```





```{r echo=F, eval=F, message=F , warning= FALSE}

generalno <- c("crkva", "biskup", "Kaptol", "časna sestra", "svećenik", "župnik", "vjernik", "kardinal", "papa", "sveti otac", "redovnik", "redovnica","kršćanstvo", "vjera", "Gospa", "Bog", "Isus", "katolički", "misa", "pričest", "krizma", "grijeh", "vjeroučitelj", "vjeronauk", "blagoslov","svjedočanstvo", "relikvija", "stigma", "duhovnost", "don", "fra", "velečasni","zaređenje", "krunica", "vjeronauk", "ukazanje") %>% tolower()
genralno_root <- sapply(generalno, write_tokens)
genralno_root <- sapply(strsplit(genralno_root, "\t"), `[`, 2)

generalno <- enframe(genralno_root, name = "name", value = "root")




imena <- c("Stepinac","Damir", "Stojić", "Željka" ,"Markić", "Ike", "Mandurić","Vlado", "Košić","Robert" ,"Bajruši", "Inoslav", "Bešker", "Ante" ,"Tomić", "Branimir" ,"Pofuk", "Igor", "Lasić", "Hrvoje", "Marjanović","Bozanić", "Ksenija" ,"Abramović", "Drago","Pilsel") %>% tolower()
imena_root <- sapply(imena, write_tokens)
imena_root <- sapply(strsplit(imena_root, "\t"), `[`, 2)

imena <- enframe(imena_root, name = "name", value = "root")



institucije  <- c("Ksaver", "HBK", "Opus Dei", "Udruga Protagora","Caritas") %>% tolower()
institucije_root <- sapply(institucije, write_tokens)
institucije_root <- sapply(strsplit(institucije_root, "\t"), `[`, 2)

institucije <- enframe(institucije_root, name = "name", value = "root")



pravno <- c("vatikanski", "ugovori", "plaćanje", "blagoslova","sakramenata", "nekretnine", "imovina") %>% tolower()
pravno_root <- sapply(pravno, write_tokens)
pravno_root <- sapply(strsplit(pravno_root, "\t"), `[`, 2)

pravno <- enframe(pravno_root, name = "name", value = "root")



politika <- C("Hod za život", "U ime obitelji", "prolife", "poništenje Rimskih ugovora", "sekularizacija", "sekularna država", "klerikalizam", "Crkva ruši vlast", "veličaju ustaštvo", "oduzimaju prava ženama", "žele stvoriti katoličku državu", "crkvena afera", "zataškavanje Kaptola", "šutnja Kaptola", "Rimski ugovori","vjeronauk u školama", "vatikanski ugovori", "vatikanska banka" ,"klerikalna vlast","država nije odvojena od Crkve", "potiče homofobiju", "rodna ideologija", "klerikalizam", "ravnozemljaši", "gay brak", "podržavali ustaše", "podržavali naciste", "blagoslovili rat", "Hrvatska nije sekularna država","Katolička crkva vlada Hrvatskom","žene u Crkvi") %>% tolower()




fraze <- c("pedofilija", "klečavci", "kaptolaši", "popovi lopovi", "zatucani katolici", "katolički fanatici", "katolički fašisti", "katolibani","crkvenjak", "ekstremni vjernici") %>% tolower()
fraze_root <- sapply(fraze, write_tokens)
fraze_root <- sapply(strsplit(fraze_root, "\t"), `[`, 2)

fraze <- enframe(fraze_root, name = "name", value = "root")










pomocno <- c( "smijenjen","konzervativci", "tradicionalisti", "pobačaj", "abortus", "aktivisti", "aktivizam", "jezuiti", "nazadan", "zaostao", "neobrazovan", "privilegije" , "privilegiran", "diskriminacija", "nacionalizam", "nacionalisti", "ekstremisti", "otpušten", "prekrštavanje", "izopćen", "izbačen", "bludničio",  "posvećenje", "inkardiniran", "inkardinacija",  "mračno doba", "razotkrio", "prijavio", "bludničio", "pronevjerio", "homofobijam", "zlodjela", "progoni", "dogma", "kontroverzni svećenik", "moderni svećenik", "tolerantna vjera", "vjerska policija", "vjerska kontrola", "crkveni mediji", "vjerski mediji", "ukidanje", "homofob", "pedofil", "homoseksualnost", "patrijarhat", "čudesno ozdravljenje", "čudo") %>% tolower()
 
pomocno_root <- sapply(pomocno, write_tokens)
pomocno_root <- sapply(strsplit(pomocno_root, "\t"), `[`, 2)

pomocno <- enframe(pomocno_root, name = "name", value = "root")

```

# imena
```{r echo=F, eval=F, message=F , warning= FALSE}

imena <- c("Stepinac","Stojić","Markić", "Mandurić", "Košić" ,"Bajruši", "Bešker","Tomić","Pofuk",  "Lasić", "Marjanović","Bozanić", "Abramović", "Pilsel") %>% tolower()


pattern_imena <- str_c("\\b(", str_c(imena, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble() %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(imena, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

imena <- bind_rows(results)

filtered_imena <- imena %>%
  filter(str_detect(full_text, pattern_imena))



#write_xlsx(imena,"D:/LUKA/Academic/HKS/Projekti/Dezinformacije/Data/imena.xlsx")


filtered_imena %>% group_by(key_word) %>% count() %>% arrange(desc(n))



```
 
 
 
 
 
# fraze
```{r echo=F, eval=F, message=F , warning= FALSE}

fraze <- c("pedofilija", "klečavci", "kaptolaši", "popovi", "lopovi", "zatucani" , "fanatici", "fašisti", "katolibani","crkvenjak", "ekstremni")
fraze_root <- sapply(fraze, write_tokens)
fraze_root <- sapply(strsplit(fraze_root, "\t"), `[`, 2)
fraze <- enframe(fraze_root, name = "name", value = "root")

pattern_fraze <- str_c("\\b(", str_c(fraze$root, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble() %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(fraze, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

fraze <- bind_rows(results)


write_xlsx(fraze,"D:/LUKA/Academic/HKS/Projekti/Dezinformacije/Data/fraze.xlsx")




filtered_df <- fraze %>%
  filter(str_detect(full_text, pattern_fraze))

filtered_df %>% group_by(key_word) %>% count() %>% arrange(desc(n))
```

# pravno
```{r echo=F, eval=F, message=F , warning= FALSE}

pravno <- c("vatikanski", "ugovori", "plaćanje", "blagoslova","sakramenata", "nekretnine", "imovina")

pattern_pravno <- str_c("\\b(", str_c(pravno, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble()  %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(pravno, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

pravno <- bind_rows(results)

filtered_df <- pravno %>%
  filter(str_detect(full_text, pattern_pravno))

filtered_df %>% group_by(key_word) %>% count() %>% arrange(desc(n))
```

# institucije
```{r echo=F, eval=F, message=F , warning= FALSE}
institucije  <- c("Ksaver", "HBK", "Opus Dei", "Udruga Protagora","Caritas") %>% tolower()


pattern_institucije <- str_c("\\b(", str_c(institucije, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble() %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(institucije, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

institucije <- bind_rows(results)

filtered_df <- institucije %>%
  filter(str_detect(full_text, pattern_institucije))

filtered_df %>% group_by(key_word) %>% count() %>% arrange(desc(n))

```


# politika
```{r echo=F, eval=F, message=F , warning= FALSE}
politika <- c("Hod","život", "obitelji", "prolife", "poništenje", "ugovora", "sekularizacija", "sekularna","država", "klerikalizam", "ruši","vlast", "veličaju" ,"ustaštvo", "oduzimaju", "prava", "ženama", "katoličku","državu", "afera", "zataškavanje", "Kaptol", "šutnja", "Rimski","vjeronauk" ,"škola", "vatikanski", "ugovori", "vatikanska", "banka" ,"klerikalna", "vlast","država","odvojena", "potiče", "homofobiju", "rodna", "ideologija", "klerikalizam", "ravnozemljaši", "gay", "brak", "podržavali", "ustaše", "podržavali", "naciste", "blagoslovili", "rat", "Hrvatska", "sekularna","katolička", "crkva", "vlada","Hrvatskom","žene") %>% tolower()


pattern_politika <- str_c("\\b(", str_c(politika, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble()  %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(politika, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

politika <- bind_rows(results)

filtered_df <- politika %>%
  filter(str_detect(full_text, pattern_politika))

filtered_df %>% group_by(key_word) %>% count() %>% arrange(desc(n))

```




# pomocno

```{r echo=F, eval=F, message=F , warning= FALSE}
pomocno <- c( "smijenjen","konzervativci", "tradicionalisti", "pobačaj", "abortus", "aktivisti", "aktivizam", "jezuiti", "nazadan", "zaostao", "neobrazovan", "privilegije" , "privilegiran", "diskriminacija", "nacionalizam", "nacionalisti", "ekstremisti", "otpušten", "prekrštavanje", "izopćen", "izbačen", "bludničio",  "posvećenje", "inkardiniran", "inkardinacija",  "mračno doba", "razotkrio", "prijavio", "bludničio", "pronevjerio", "homofobijam", "zlodjela", "progoni", "dogma", "kontroverzni" , "moderni", "svećenik", "tolerantna", "vjera", "vjerska", "policija", "vjerska", "kontrola", "crkveni", "mediji", "vjerski" ,"mediji", "ukidanje", "homofob", "pedofil", "homoseksualnost", "patrijarhat", "čudesno" , "ozdravljenje", "čudo")


pattern_pomocno <- str_c("\\b(", str_c(pomocno, collapse = "|"), ")\\b")


# Define the batch size
batch_size <- 1000

# Split your data into batches
batches <- split(dt, ceiling(seq_along(dt[[1]])/batch_size))

# Function to process each batch
process_batch <- function(batch) {
  batch %>%
    as_tibble() %>%
    select(V1, DATE, TITLE, URL, FULL_TEXT) %>%
    mutate(
      full_text = tolower(FULL_TEXT),
      match = str_c(pomocno, collapse = '|'),
      key_word = str_extract_all(full_text, match)
    ) %>%
    filter(lengths(key_word) > 0) %>%
    unnest(key_word) %>%
    distinct(V1, .keep_all = TRUE)
}

# Process each batch
results <- batches %>%
  map(~ process_batch(.x))

pomocno <- bind_rows(results)

filtered_df <- pomocno %>%
  filter(str_detect(full_text, pattern_pomocno))





```





filtered_df %>% group_by(key_word) %>% count() %>% arrange(desc(n))






```{r}


dta <- dt %>%
 # filter(SOURCE_TYPE =="web")  %>%
  filter(str_detect(FULL_TEXT,fixed("stojić",ignore_case = TRUE)))





dta <- dt %>%
  filter(SOURCE_TYPE =="web")  %>%
  filter(str_detect(URL,fixed("836688",ignore_case = TRUE)))


activity <- dta %>%
  group_by(FROM) %>%
  summarise(count = n()) %>%
  mutate(percent = round(count / sum(count) * 100,2)) %>% 
  arrange(desc(count))

datatable(activity, options = list(scrollX = TRUE, scrollY = "500px"))


dta %>% 
  select(DATE,TIME,TITLE,FROM,AUTHOR,URL, FULL_TEXT) %>%
  datatable(., options = list(scrollX = TRUE, scrollY = "500px"))



```


