---
title: "Pregled hrvatskog YouTube-a"
author: "Lux"
date: '28 06 2021 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(cowplot)
library(magick)
library(png)
library(RCurl)
library(patchwork) 
library(grid)
library(ggpubr)
```


## Općenito o YouTube platformi



## YouTube u Hrvatskoj

```{r data}
yt <- read.csv2("../data/topYT.csv")
```

## Najpopularnije kategorije kanala

```{r kanali, echo=FALSE}
kanali <- yt %>%
  group_by(genre) %>%
  count() %>%
  arrange(.,desc(n)) %>%
  ungroup() %>%
  slice(.,1:(n()-1))

img <- jpeg::readJPEG("../Foto/yt8.jpg")
 
topGenre <- ggplot(kanali, aes(x = n, y = reorder(genre,n))) +
  background_image(img) +
  geom_bar(stat = "identity", alpha = 1) +
  ylab("") +
  xlab("Number of channels") +
  ggtitle("Top (1k) Croatian YouTube channels by genre")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
  panel.background = element_blank(), axis.line = element_line(colour = "black")) 


```







