---
title: "Learning Social Media Analytics"
# subtitle: "<html><div style='float:left'></div><hr color='#EB811B' size=1px width=796px></html>"
subtitle: "Lecture 2: Current state and latest trends"
author: "Luka Sikic, PhD"
date: "Faculty of Croatian Studies | [LSMA](https://lusiki.github.io/Learning-Social-Media-Analytics/)" #"`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: [default, metropolis, metropolis-fonts] 
    lib_dir: libs
    nature:
      highlightStyle: googlecode
      highlightLines: true
      countIncrementalSlides: false

---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```


```{r libs, include=TRUE, echo=FALSE,message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(kableExtra)
library(DT)
```


# STRUCTURE
<br>
<br>
<br>
<br>
- DATA EXPLORATION
<br>
<br>
- 
<br>
<br>
- 
<br>
<br>
- 
<br>
<br>

---
layout: true
# DATA EXPLORATION
---

- check the raw [data](https://github.com/lusiki/Learning-Social-Media-Analytics/blob/main/data/Mediatoolkit/sample.xlsx); sourced from [Mediatoolkit](https://www.mediatoolkit.com/)



```{r, echo=T}
# read into environment
one_day_sample <- read_excel(here::here("data/Mediatoolkit/sample.xlsx"))
# size of the data
dim(one_day_sample)
# sneek peak
glimpse(one_day_sample[sample(nrow(one_day_sample)),1:8])

```

---
<br>
<br>
<br>
```{r}
# other variables
names(one_day_sample)
```

---

```{r, echo=T}
# dates
unique(one_day_sample$DATE)
# time
length(unique(one_day_sample$TIME))
# observations/ activity
nrow(one_day_sample)
# social media networks
unique(one_day_sample$SOURCE_TYPE)


```

---


```{r, echo=T}
# unique authors
length(unique(one_day_sample$AUTHOR))
# unique titles
length(unique(one_day_sample$TITLE))
# unique sources
length(unique(one_day_sample$FROM))
# unique urls
length(unique(one_day_sample$URL))
```

---

```{r, echo=T}
# GENERAL OVERVIEW
one_day_sample %>%
  group_by(SOURCE_TYPE) %>%
  count() %>%
  arrange(desc(n)) %>%
  mutate_if(is.numeric, format, big.mark = ".") %>%
  kbl() %>%
  kable_styling(font_size = 11)
```

---

```{r, echo=T}
# SAMPLE SOME TXT
one_day_sample %>%
     select(SOURCE_TYPE, MENTION_SNIPPET) %>%
     unique(.) %>%  
     sample_n(9) %>%
  kbl() %>%
  kable_styling(font_size = 11)
```


---

```{r, echo=T}
# SAMPLE SOME TITLES
one_day_sample %>%
     select(SOURCE_TYPE, TITLE) %>%
     unique(.) %>%  
     sample_n(9) %>%
  kbl() %>%
  kable_styling(font_size = 11)
```


---








```{r, eval = F}

path <- "D:/LUKA/Freelance/Mediatoolkit/FULLDATA"

raw <- list.files(path = path , pattern="xlsx")

raw_path <- paste0(path, "/", raw)

all_raw <- map_df(raw_path[1:5], read_excel)
```




---
<br>
#### 
<br>
<br>
<br>
-
<br>
<br>
- 
<br>
<br>
- l
<br>
<br>
-

---